version: '3.8'

services:

  php:
    env_file:
      - .env.docker
    container_name: tidio-php
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - 80:80

  postgres:
    image: postgres:13-alpine
    container_name: tidio-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

volumes:
  db-data: